# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [5]:
import numpy as np
#just for code consistency I have moved this import up top
from PIL import Image

**2. Print the numpy version and the configuration**

In [4]:
print(np.__version__)
print(np.show_config())

1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
   

**3. Create a 1D array of zeros of size 10 of type float32**

In [5]:
array_zeros = np.zeros(10, dtype=np.float32)
print("\n1D Array of Zeros (float32):\n", array_zeros)


1D Array of Zeros (float32):
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [6]:
Z = np.zeros((32,12))
# Include your solution below
print("\nMemory size of Z:", Z.nbytes, "bytes")


Memory size of Z: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [7]:
array_values = np.arange(10, 59)
print("\n1D Array with Values Ranging from 10 to 58:\n", array_values)


1D Array with Values Ranging from 10 to 58:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [9]:
a = np.arange(10)
# Include your solution below
reversed_a = a[::-1]
print("\nReversed Vector:\n", reversed_a)


Reversed Vector:
 [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with Values Ranging from 0 to 8:\n", matrix_3x3)


3x3 Matrix with Values Ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [11]:
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [13]:
Z = np.random.random((10,11))
# Include your solution below


In [14]:
max_values_columns = np.max(Z, axis=0)
print("\nMaximum Values of Each Column:\n", max_values_columns)


Maximum Values of Each Column:
 [0.89802609 0.99040387 0.99431925 0.90599221 0.9880566  0.75460485
 0.88684954 0.84209312 0.90022536 0.88994747 0.98478332]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [15]:
array_borders = np.ones((5, 5))
array_borders[1:-1, 1:-1] = 0
print("\n2D Array with 1s on Borders:\n", array_borders)


2D Array with 1s on Borders:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [16]:
Z = np.ones((5,5))
# Include your solution below
Z_padded = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print("\nPadded Array:\n", Z_padded)


Padded Array:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [17]:
Z = np.random.uniform(0,10,10)
# Include your solution below
integer_part = np.floor(Z)
print("\nInteger Part of Random Array:\n", integer_part)


Integer Part of Random Array:
 [3. 5. 6. 0. 6. 6. 3. 4. 0. 0.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [18]:
matrix_equal_rows = np.zeros((5,5)) + np.arange(5)
print("\n5x5 Matrix with Equal Value Rows:\n", matrix_equal_rows)


5x5 Matrix with Equal Value Rows:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [19]:
vector_range_01 = np.linspace(0, 1, 12)[1:-1]
print("\nVector of Size 10 Ranging from 0 to 1:\n", vector_range_01)


Vector of Size 10 Ranging from 0 to 1:
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [20]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("\nSorted Random Vector:\n", sorted_vector)


Sorted Random Vector:
 [0.00882048 0.04922407 0.18256754 0.26823742 0.33733601 0.33918679
 0.45862328 0.47771184 0.69132891 0.91288442]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [21]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print("\nCartesian Coordinates (X,Y):\n", Z)
print("\nPolar Coordinates (R, Theta):\n", np.column_stack((R,T)))


Cartesian Coordinates (X,Y):
 [[0.13269482 0.8051714 ]
 [0.03591017 0.23695027]
 [0.06169769 0.98289759]
 [0.31828575 0.80579397]
 [0.48883176 0.44421887]
 [0.07741141 0.75946502]
 [0.88260608 0.99208527]
 [0.73582849 0.69631009]
 [0.4307477  0.94392824]
 [0.04239042 0.20704651]]

Polar Coordinates (R, Theta):
 [[0.81603241 1.4074613 ]
 [0.23965594 1.42038937]
 [0.98483211 1.50810734]
 [0.86637736 1.19461079]
 [0.66052017 0.73762054]
 [0.76340006 1.46921827]
 [1.32786546 0.84373043]
 [1.01306037 0.75781118]
 [1.03756643 1.14268654]
 [0.21134144 1.36884857]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [40]:
random_vector_origin = np.random.random(10)
print("\nRandom Vector without Maximum Value Replaced by 0:\n", random_vector_origin)
random_vector_origin[random_vector_origin.argmax()] = '0'
print("\nRandom Vector with Maximum Value Replaced by 0:\n", random_vector_origin)


Random Vector without Maximum Value Replaced by 0:
 [0.06873401 0.05369503 0.56616859 0.78249676 0.82781264 0.72108943
 0.94906379 0.15306235 0.9629244  0.07726749]

Random Vector with Maximum Value Replaced by 0:
 [0.06873401 0.05369503 0.56616859 0.78249676 0.82781264 0.72108943
 0.94906379 0.15306235 0.         0.07726749]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [41]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
nearest_value = Z[np.abs(Z - z).argmin()]
print("\nNearest Value to", z, "in Array Z:", nearest_value)


Nearest Value to 0.5 in Array Z: 0.505781197165011


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [42]:
Z = np.arange(5)[::-1]
# Include your solution below
new_vector = np.zeros(len(Z) + (len(Z)-1) * 3)
new_vector[::4] = Z
print("\nNew Vector with 3 Consecutive Zeros Interleaved:\n", new_vector)


New Vector with 3 Consecutive Zeros Interleaved:
 [4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [43]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
result = A * B[:,:,None]
print("\nElement-wise Multiplication Result:\n", result)



Element-wise Multiplication Result:
 [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [44]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
W[[0, 1]] = W[[1, 0]]
print("\nSwapped Rows in 2D Array:\n", W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


Swapped Rows in 2D Array:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [7]:
# This bit of code allows to check if jupyter has access to the files in Figures, important because not always the images
# are loaded from the correct folder.
import os
files = [f for f in os.listdir('./Figures/') if os.path.isfile(f)]
for f in files:
    print("FileFound")

In [9]:
def bbox(img):
    #include your solution below
    rows = np.any(img, axis=1)
    cols = np.any(img, axis=0)
    r1, r2 = np.where(rows)[0][[0, -1]]
    c1, c2 = np.where(cols)[0][[0, -1]]
    return (r1,c1),(r2,c2)




img = np.array(Image.open('./Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


REASONING:                                                                                              
In image processing and computer vision tasks, determining the bounding box of an object is crucial for tasks like object detection and segmentation.
The function bbox(img) takes a 2D Boolean NumPy array img as input, where True represents the presence of an object and False represents the background.
The function works by first finding rows and columns where any non-zero (i.e., True) values exist using np.any(). This gives us the coordinates of the bounding box.
Then, I use np.where() to find the indices of the first and last non-zero elements along each axis, giving us the coordinates of the top-left and bottom-right corners of the bounding box.
Finally, we return these coordinates as a tuple (r1,c1),(r2,c2) representing the top-left and bottom-right corners of the bounding box.

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [11]:
def moving_average(x,N):
    return np.convolve(x, np.ones(N), 'valid') / N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]


REASONING:
A moving average is a calculation used to analyze data points by creating a series of averages of different subsets of the full data set. It's useful for smoothing out short-term fluctuations and highlighting longer-term trends.
The function moving_average(x, N=3) takes a 1D NumPy array x and an optional parameter N specifying the length of the sliding window.
It uses np.convolve() to convolve the input array x with a window of ones of length N. This operation effectively calculates the sum of each window.
Then, it divides the result by N to compute the average over each window.
The 'valid' mode in np.convolve() ensures that the output array only contains values where the window fully overlaps with the input array, avoiding edge effects.
The function returns an array containing the moving averages.

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [12]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
A = np.repeat(np.arange(len(C)), C)
print("\nArray A such that np.bincount(A) == C:", A)

[0 2 1 1 2 0 1]

Array A such that np.bincount(A) == C: [1 1 2 3 4 4 6]


REASONING:
np.bincount() is a function that counts occurrences of each value in an array of non-negative integers.
In this question, I start with an array C that corresponds to the output of np.bincount() on another array.
The goal is to create an array A such that np.bincount(A) equals C.
To achieve this, I use np.repeat() to repeat each index in the range of len(C) by the corresponding count in C.
This ensures that when np.bincount() is applied to A, the resulting counts match those in C.
The resulting array A thus fulfills the requirement of having a bincount equal to C.

**25. Find the most frequent value in the array below?**

In [13]:
Z = np.random.randint(0,10,50)
# Include your solution below
most_frequent_value = np.bincount(Z).argmax()
print("\nMost Frequent Value in the Array:", most_frequent_value)



Most Frequent Value in the Array: 8


**26. Write a function to return the n largest values of an array** 

In [17]:
def nlargest(a,n):
    # Include your solution here
    return np.sort(a)[-n:]
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[9995 9996 9997 9998 9999]
